[package]
name = "optipng-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
decoder = { path = "../png_stream_dec/decoder" }
encoder = { path = "../png_stream_enc/encoder" }
clap = { version = "4.0", features = ["derive"] }
owo-colors = "4.0"
libc = "0.2"

[[bin]]
name = "optipng-rs"
path = "src/main.rs"
