[package]
name = "optipng-rs"
version = "0.3.1"
edition = "2024"

[dependencies]
decoder = { path = "../png_stream_dec/decoder" }
encoder = { path = "../png_stream_enc/encoder" }
owo-colors = "4.0"
indicatif = "0.17"
sysinfo = "0.30"
console = "0.15"

[[bin]]
name = "optipng-rs"
path = "src/main.rs"
